title: 'b2a3e8.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
url: "https://b2a3e8.github.io"

header_pages:
  - index.md
  - about.md
  - projects.md
  - photos.md

style: light 

footer: '<a href="https://github.com/olivergoodman/" target="_blank">github</a> 
        <a href="https://linkedin.com/in/oliverbgoodman/" target="_blank">linkedin</a>
        <a href="https://letterboxd.com/ollygreatman/" target="_blank">letterboxd</a>
        <a href="https://linkedin.com/in/oliverbgoodman/" target="_blank">email</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

theme: jekyll-theme-console
